package com.model;

/**
 * TBaoxiu generated by MyEclipse Persistence Tools
 */

/**
 * @author Administrator
 *
 */
public class TBaoxiu implements java.io.Serializable
{

	private Integer id;
	private String shijian;
	private String yuanyin;
	private String sushe;
	
	private int stuId;
	private String zhuangtai;
	private String del;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public int getStuId()
	{
		return stuId;
	}
	public void setStuId(int stuId)
	{
		this.stuId = stuId;
	}
	public String getSushe()
	{
		return sushe;
	}
	public void setSushe(String sushe)
	{
		this.sushe = sushe;
	}
	public String getYuanyin()
	{
		return yuanyin;
	}
	public void setYuanyin(String yuanyin)
	{
		this.yuanyin = yuanyin;
	}
	public String getZhuangtai()
	{
		return zhuangtai;
	}
	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}

}