/*
 *
 * Created on __DATE__, __TIME__
 */

package com.jakey.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class MainFrm_admin extends javax.swing.JFrame {

	/** Creates new form MainFrm_admin */
	public MainFrm_admin() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jmiCourseView = new javax.swing.JMenuItem();
		jmiCourseAdd = new javax.swing.JMenuItem();
		jmiCourseManage = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jmiStudentView = new javax.swing.JMenuItem();
		jmiStudentPassword = new javax.swing.JMenuItem();
		jmiExit = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u9009\u8bfe\u7cfb\u7edf_\u7ba1\u7406\u5458\u7aef");

		jMenu1
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\base.png")); // NOI18N
		jMenu1.setText("\u57fa\u672c\u64cd\u4f5c");

		jMenu3
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\course.png")); // NOI18N
		jMenu3.setText("\u9009\u8bfe\u76f8\u5173");

		jmiCourseView
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\course.png")); // NOI18N
		jmiCourseView.setText("\u67e5\u770b\u9009\u8bfe\u60c5\u51b5");
		jmiCourseView.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiCourseViewActionPerformed(evt);
			}
		});
		jMenu3.add(jmiCourseView);

		jmiCourseAdd
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\course.png")); // NOI18N
		jmiCourseAdd.setText("\u589e\u52a0\u8bfe\u7a0b\u6761\u76ee");
		jmiCourseAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiCourseAddActionPerformed(evt);
			}
		});
		jMenu3.add(jmiCourseAdd);

		jmiCourseManage
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\course.png")); // NOI18N
		jmiCourseManage.setText("\u4fee\u6539\u8bfe\u7a0b\u4fe1\u606f");
		jmiCourseManage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiCourseManageActionPerformed(evt);
			}
		});
		jMenu3.add(jmiCourseManage);

		jMenu1.add(jMenu3);

		jMenu4
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\student.png")); // NOI18N
		jMenu4.setText("\u5b66\u751f\u76f8\u5173");

		jmiStudentView
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\student.png")); // NOI18N
		jmiStudentView.setText("\u67e5\u770b\u5b66\u751f\u8d44\u6599");
		jmiStudentView.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiStudentViewActionPerformed(evt);
			}
		});
		jMenu4.add(jmiStudentView);

		jmiStudentPassword
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\password.png")); // NOI18N
		jmiStudentPassword.setText("\u7ba1\u7406\u5b66\u751f\u5bc6\u7801");
		jmiStudentPassword
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jmiStudentPasswordActionPerformed(evt);
					}
				});
		jMenu4.add(jmiStudentPassword);

		jMenu1.add(jMenu4);

		jmiExit
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\exit.png")); // NOI18N
		jmiExit.setText("\u9000\u51fa\u7cfb\u7edf");
		jmiExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiExitActionPerformed(evt);
			}
		});
		jMenu1.add(jmiExit);

		jMenuBar1.add(jMenu1);

		jMenu2
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\help.png")); // NOI18N
		jMenu2.setText("\u5e2e\u52a9");

		jMenuItem1
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\help.png")); // NOI18N
		jMenuItem1.setText("\u64cd\u4f5c\u6307\u5357");
		jMenu2.add(jMenuItem1);

		jMenuItem2
				.setIcon(new javax.swing.ImageIcon(
						"D:\\Workspaces\\MyEclipse 8.5\\CourseSys\\src\\com\\jakey\\view\\image\\phone.png")); // NOI18N
		jMenuItem2.setText("\u8054\u7cfb\u6280\u672f\u4eba\u5458");
		jMenu2.add(jMenuItem2);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jmiStudentPasswordActionPerformed(
			java.awt.event.ActionEvent evt) {
		StudentPasswordInterFrm studentPasswordInterFrm = new StudentPasswordInterFrm();
		studentPasswordInterFrm.setVisible(true);
		this.table.add(studentPasswordInterFrm);
	}

	private void jmiStudentViewActionPerformed(java.awt.event.ActionEvent evt) {
		StudentViewInterFrm studentViewInterFrm = new StudentViewInterFrm();
		studentViewInterFrm.setVisible(true);
		this.table.add(studentViewInterFrm);
	}

	private void jmiCourseViewActionPerformed(java.awt.event.ActionEvent evt) {
		CourseViewInterFrm courseViewInterFrm = new CourseViewInterFrm();
		courseViewInterFrm.setVisible(true);
		this.table.add(courseViewInterFrm);
	}

	private void jmiCourseManageActionPerformed(java.awt.event.ActionEvent evt) {
		CourseManageInterFrm courseManageInterFrm = new CourseManageInterFrm();
		courseManageInterFrm.setVisible(true);
		this.table.add(courseManageInterFrm);
	}

	private void jmiCourseAddActionPerformed(java.awt.event.ActionEvent evt) {
		CourseAddInterFrm courseAddInterFrm = new CourseAddInterFrm();
		courseAddInterFrm.setVisible(true);
		this.table.add(courseAddInterFrm);
	}

	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(this, "是否退出系统");
		if (result == 0) {
			this.dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm_admin().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jmiCourseAdd;
	private javax.swing.JMenuItem jmiCourseManage;
	private javax.swing.JMenuItem jmiCourseView;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiStudentPassword;
	private javax.swing.JMenuItem jmiStudentView;
	private javax.swing.JDesktopPane table;
	// End of variables declaration//GEN-END:variables

}